name: staticCheck
description: static check
inputs:
  repo_name:
    description: 'repo name'
    required: false
    default: ${{github.repository}}
outputs:
  summary-result:
    description: summary result
    value: ${{ steps.get-summary-result.outputs.summary-result }}
  summary-status:
    description: summary status
    value: ${{ steps.get-summary-result.outputs.summary-status }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo_name }}
        ref: ${{ github.event.pull_request.head.sha }}
    - id: change-file-lang
      uses: reviews-team-test/ci-check-action/actions/change-file-lang@check-tools
    - id: golangci-lint
      if: steps.change-file-lang.outputs.isGo == 'true'
      uses: reviews-team-test/ci-check-action/actions/golangci-lint@static-check
    - id: cppcheck
      if: always() && steps.change-file-lang.outputs.isC == 'true'
      uses: reviews-team-test/ci-check-action/actions/cpp-check@static-check
    - id: shellcheck
      if: always() && steps.change-file-lang.outputs.isSh == 'true'
      uses: reviews-team-test/ci-check-action/actions/shell-check@static-check
    - id: get-summary-result
      if: always()
      shell: bash
      run: |
        echo "summary-result=$goResult|$cppResult|$shellResult" >> $GITHUB_OUTPUT
        echo "summary-status=[${goStatus},${cppStatus},${shellStatus}]" >> $GITHUB_OUTPUT
      env:
        goResult: ${{ steps.golangci-lint.outputs.isFailed != 'true' && '0' || steps.golangci-lint.outputs.errNum }}
        cppResult: ${{ steps.cppcheck.outputs.isFailed != 'true' && '0' || steps.cppcheck.outputs.errNum }}
        shellResult: ${{ steps.shellcheck.outputs.isFailed != 'true' && '0' || steps.shellcheck.outputs.errNum }}
        goStatus: ${{ steps.golangci-lint.outputs.isFailed }}
        cppStatus: ${{ steps.cppcheck.outputs.isFailed }}
        shellStatus: ${{ steps.shellcheck.outputs.isFailed }}
