name: 'Post-Check'
description: 'Post Step After Check, eg. comment, add reviewers'
inputs:
  testtype:
    description: 'test type'
    required: true
    default: 'staticCheck'
  status:
    description: 'status of check result'
    required: true
    default: '是'
  result:
    description: 'result'
    required: true
    default: '0'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: kuchune/check-tools
        sparse-checkout: |
          common/sendData.py
        sparse-checkout-cone-mode: false
    - run: python3 common/sendData.py
      shell: bash
      env:
        PROJECT: "${{github.repository}}"
        NUMBER: "${{github.event.pull_request.number}}"
        REVISION: "${{github.event.pull_request.head.sha}}"
        RUNID: "${{github.run_id}}"
        JOBSTATUS: "${{job.status}}"
        TESTTYPE: ${{ inputs.testtype }}
        STATUS: ${{ inputs.status }}
        RESULT: ${{ inputs.result }}