name: 'Send-Data-to-MDY'
description: 'send check data to mdy'
inputs:
  status:
    description: 'show value'
    required: false
    default: 'staticCheck'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo ${{ inputs.status }}