name: 'Post-Check'
description: 'Post Step After Check, eg. comment, add reviewers'
inputs:
  token:
    description: 'token '
    required: false
    default: ${{github.token}}
  comment-file:
    description: 'comment file path'
    required: false
    default: 'comment.txt'
  reviewers:
    description: 'comment file path'
    required: true

runs:
  using: "composite"
  steps:
    - uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ${{inputs.comment-file}}
    - uses: ryaugusta/pr-add-reviewers-action@v1
      with:
        token: ${{ inputs.token }}
        reviewers: ${{ inputs.reviewers }}