name: 'Cpp-Check'
description: 'cpp check'
inputs:
  repo_name:
    description: 'repo name'
    required: false
    default: ${{github.repository}}
  change_files:
    description: 'change files'
    required: false
    default: ''
  scandir:
    description: 'scan dir'
    required: false
    default: '.'

outputs:
  isFailed:
    description: 'isFailed'
    value: ${{ steps.get-check-flag.outputs.isFailed }}
  errNum:
    description: 'errNum'
    value: ${{ steps.get-check-flag.outputs.errNum }}

runs:
  using: "composite"
  steps:
    - uses: reviews-team-test/action-cppcheck@main
      with:
        repository: ${{ inputs.repo_name }}
        pull_request_id: ${{ github.event.pull_request.number }}
        allow_approve: false
        scandir: ${{ inputs.scandir }}
    - id: get-check-flag
      if: always()
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ inputs.change_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file" | tee -a change_files.txt
        done
        python3 $GITHUB_ACTION_PATH/static_tools_filter.py --type cppcheck --file change_files.txt --xml ./report.xml || true
        errNum=$(egrep "[[:space:]]+<error .*severity=\"error\"" report_new.xml | wc -l || true)
        if [ "$errNum" -gt "0" ];then
            echo "cppcheck检查失败"
            echo "isFailed=true" >> $GITHUB_OUTPUT
        fi
        echo "errNum=$errNum" >> $GITHUB_OUTPUT